const mongoose = require('mongoose');
const User = require('../models/User');
require('dotenv').config();

// Sample user data based on provided CSV
const userData = [
    {
        email: 'abdul.mansyur@millennia21.id',
        password: 'password123',
        name: 'Abdul Mansyur',
        username: 'Mansyur',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Boy',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-10-09'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'abdullah@millennia21.id',
        password: 'password123',
        name: 'Abdullah, SE, MM',
        username: 'Abdul',
        role: 'staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Staff Resources',
        employmentStatus: 'Permanent',
        joinDate: new Date('2005-01-31')
    },
    {
        email: 'abu@millennia21.id',
        password: 'password123',
        name: 'Abu Bakar Ali, S.Sos I',
        username: 'Abu',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2002-06-03')
    },
    {
        email: 'adibah.hana@millennia21.id',
        password: 'password123',
        name: 'Adibah Hana Widjaya',
        username: 'Adibah',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Librarian',
        employmentStatus: 'Contract',
        joinDate: new Date('2025-02-07'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'adiya.herisa@millennia21.id',
        password: 'password123',
        name: 'Adiya Herisa',
        username: 'Adiya',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Perawat',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-09-04')
    },
    {
        email: 'afiyanti.hardiansari@millennia21.id',
        password: 'password123',
        name: 'Afiyanti Hardiansari',
        username: 'Afi',
        role: 'teacher',
        department: 'Kindergarten',
        jobLevel: 'Teacher',
        unit: 'Kindergarten',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2025-04-08'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'dodi@millennia21.id',
        password: 'password123',
        name: 'Ahmad Haikal',
        username: 'Dody',
        role: 'head_unit',
        department: 'Operational',
        jobLevel: 'Head Unit',
        unit: 'Operational',
        jobPosition: 'Head of Operational',
        employmentStatus: 'Permanent',
        joinDate: new Date('2017-11-14')
    },
    {
        email: 'dhaffa@millennia21.id',
        password: 'password123',
        name: 'Alifananda Dhaffa Hanif Musyafa, S.Pd',
        username: 'Dhaffa',
        role: 'se_teacher',
        department: 'Junior High',
        jobLevel: 'SE Teacher',
        unit: 'Junior High',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2023-12-23'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'almia@millennia21.id',
        password: 'password123',
        name: 'Almia Ester Kristiyany Sinabang, S.Pd',
        username: 'Almia',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2021-06-28')
    },
    {
        email: 'anggie@millennia21.id',
        password: 'password123',
        name: 'Anggie Ayu Setya Pradini, S.Pd',
        username: 'Anggie',
        role: 'se_teacher',
        department: 'Junior High',
        jobLevel: 'SE Teacher',
        unit: 'Junior High',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-07-17')
    },
    {
        email: 'annisa.fitri@millennia21.id',
        password: 'password123',
        name: 'Annisa Fitri Tanjung',
        username: 'Ardi',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-14'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'ardiansyah@millennia21.id',
        password: 'password123',
        name: 'Ardiansyah',
        username: 'Ardi',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'PLH',
        employmentStatus: 'Permanent',
        joinDate: new Date('2018-03-01')
    },
    {
        email: 'aria@millennia21.id',
        password: 'password123',
        name: 'Aria Wisnuwardana, S.TP',
        username: 'Aria',
        role: 'head_unit',
        department: 'Junior High',
        jobLevel: 'Head Unit',
        unit: 'Junior High',
        jobPosition: 'Principal of Junior High',
        employmentStatus: 'Permanent',
        joinDate: new Date('2006-03-27')
    },
    {
        email: 'alinsuwisto@millennia21.id',
        password: 'password123',
        name: 'Auliya Hasanatin Suwisto, S.IKom',
        username: 'Alin',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2022-10-24')
    },
    {
        email: 'aprimaputri@millennia21.id',
        password: 'password123',
        name: 'Ayunda Primaputri',
        username: 'Ayunda',
        role: 'teacher',
        department: 'Kindergarten',
        jobLevel: 'Teacher',
        unit: 'Kindergarten',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-06-24'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'wina@millennia21.id',
        password: 'password123',
        name: 'Azalia Magdalena Septianti Tambunan',
        username: 'Wina',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'School\'s Psychologist',
        employmentStatus: 'Contract',
        joinDate: new Date('2025-02-03'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'belakartika@millennia21.id',
        password: 'password123',
        name: 'Bela Kartika Sari',
        username: 'Bela',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-06-24'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'nana@millennia21.id',
        password: 'password123',
        name: 'Berliana Gustina Siregar',
        username: 'Nana',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2025-04-08'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'derry@millennia21.id',
        password: 'password123',
        name: 'Derry Parmanto, S.S',
        username: 'Derry',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Staff Admin',
        employmentStatus: 'Permanent',
        joinDate: new Date('2018-11-15')
    },
    {
        email: 'devi.agriani@millennia21.id',
        password: 'password123',
        name: 'Devi Agriani, S.Pd.',
        username: 'Devi',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-06-24'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'devilarasati@millennia21.id',
        password: 'password123',
        name: 'Devi Larasati',
        username: 'Laras',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-06-24'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'dien@millennia21.id',
        password: 'password123',
        name: 'Dien Islami',
        username: 'Dien',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-14'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'dina@millennia21.id',
        password: 'password123',
        name: 'Dina',
        username: 'Dina',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Girl',
        employmentStatus: 'Permanent',
        joinDate: new Date('2022-05-25')
    },
    {
        email: 'dinimeilani@millennia21.id',
        password: 'password123',
        name: 'Dini Meilani Pramesti',
        username: 'Dini',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-06-24'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'diya@millennia21.id',
        password: 'password123',
        name: 'Diya Pratiwi, S.S',
        username: 'Diya',
        role: 'teacher',
        department: 'Kindergarten',
        jobLevel: 'Teacher',
        unit: 'Kindergarten',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2021-04-01')
    },
    {
        email: 'dona@millennia21.id',
        password: 'password123',
        name: 'Dona',
        username: 'Dona',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Girl',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-07-26'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'akbarfadholi98@millennia21.id',
        password: 'password123',
        name: 'Fadholi Akbar',
        username: 'Fadholi',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-06-24'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'faisal@millennia21.id',
        password: 'password123',
        name: 'Faisal Nur Hidayat',
        username: 'Faisal',
        role: 'head_unit',
        department: 'MAD Lab',
        jobLevel: 'Head Unit',
        unit: 'MAD Lab',
        jobPosition: 'Head of IT',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-07-15'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'fasa@millennia21.id',
        password: 'password123',
        name: 'Faqiha Salma Achmada S.Psi.',
        username: 'Fasa',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2025-04-24'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'aya@millennia21.id',
        password: 'password123',
        name: 'Farhah Alya Nabilah',
        username: 'Aya',
        role: 'staff',
        department: 'Kindergarten',
        jobLevel: 'Staff',
        unit: 'Kindergarten',
        jobPosition: 'Secretary',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-18'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'jo@millennia21.id',
        password: 'password123',
        name: 'Fayza Julia Pramesti Hapsari Prayoga',
        username: 'Jo',
        role: 'staff',
        department: 'Pelangi',
        jobLevel: 'Staff',
        unit: 'Pelangi',
        jobPosition: 'Admin Pelangi / Secretary',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-08-15'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'ferlyna.balqis@millennia21.id',
        password: 'password123',
        name: 'Ferlyna Balqis',
        username: 'Balqis',
        role: 'se_teacher',
        department: 'Kindergarten',
        jobLevel: 'SE Teacher',
        unit: 'Kindergarten',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2025-04-08'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'fransiskaeva@millennia21.id',
        password: 'password123',
        name: 'Fransiska Evasari, S.Pd',
        username: 'Eva',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2021-06-28')
    },
    {
        email: 'galen@millennia21.id',
        password: 'password123',
        name: 'Galen Rasendriya',
        username: 'Galen',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-28'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'gundah@millennia21.id',
        password: 'password123',
        name: 'Gundah Basiswi, S.Pd',
        username: 'Gundah',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-07-17')
    },
    {
        email: 'hadi@millennia21.id',
        password: 'password123',
        name: 'Hadi',
        username: 'Hadi',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'Performing Art Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-14'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'hana.fajria@millennia21.id',
        password: 'password123',
        name: 'Hana Nuzula Fajria, S.Pd',
        username: 'Hana',
        role: 'head_unit',
        department: 'Pelangi',
        jobLevel: 'Head Unit',
        unit: 'Pelangi',
        jobPosition: 'Head of Pelangi',
        employmentStatus: 'Permanent',
        joinDate: new Date('2019-09-02')
    },
    {
        email: 'himawan@millennia21.id',
        password: 'password123',
        name: 'Himawan Rizky Syaputra',
        username: 'Himawan',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'Coding Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-14'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'iis@millennia21.id',
        password: 'password123',
        name: 'Iis Asifah',
        username: 'Iis',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-14'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'ikarahayu@millennia21.id',
        password: 'password123',
        name: 'Ika Rahayu',
        username: 'Ika',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-14'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'irawan@millennia21.id',
        password: 'password123',
        name: 'Irawan',
        username: 'Iwan',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Driver',
        employmentStatus: 'Permanent',
        joinDate: new Date('2017-03-02')
    },
    {
        email: 'khairul@millennia21.id',
        password: 'password123',
        name: 'Khairul Anwar',
        username: 'Irul',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Boy',
        employmentStatus: 'Permanent',
        joinDate: new Date('2019-06-17')
    },
    {
        email: 'kholida@millennia21.id',
        password: 'password123',
        name: 'Kholida Widyawati, S.Sos, MA',
        username: 'Kholi',
        role: 'head_unit',
        department: 'Elementary',
        jobLevel: 'Head Unit',
        unit: 'Elementary',
        jobPosition: 'Principal of Elementary',
        employmentStatus: 'Permanent',
        joinDate: new Date('2019-02-25')
    },
    {
        email: 'alys@millennia21.id',
        password: 'password123',
        name: 'Krisalyssa Esna Rehulina Tarigan, S.K.Pm',
        username: 'Alys',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2023-07-17'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'sandi@millennia21.id',
        password: 'password123',
        name: 'Kurnia Sandi',
        username: 'Sandi',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Boy',
        employmentStatus: 'Permanent',
        joinDate: new Date('2018-09-24')
    },
    {
        email: 'latifah@millennia21.id',
        password: 'password123',
        name: 'Latifah Nur Restiningtyas, S.Pd',
        username: 'Latifah',
        role: 'head_unit',
        department: 'Kindergarten',
        jobLevel: 'Head Unit',
        unit: 'Kindergarten',
        jobPosition: 'Principal of Kindergarten',
        employmentStatus: 'Permanent',
        joinDate: new Date('2022-07-18')
    },
    {
        email: 'mahrukh@millennia21.id',
        password: 'password123',
        name: 'Mahrukh Bashir',
        username: 'Ms. Mahrukh',
        role: 'directorate',
        department: 'Directorate',
        jobLevel: 'Director',
        unit: 'Directorate',
        jobPosition: 'Academic Director',
        employmentStatus: 'Permanent',
        joinDate: new Date('2009-10-01')
    },
    {
        email: 'maria@millennia21.id',
        password: 'password123',
        name: 'Maria Rosa Apriliana Jaftoran',
        username: 'Maria',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2022-07-18')
    },
    {
        email: 'maulida.yunita@millennia21.id',
        password: 'password123',
        name: 'Maulida Yunita',
        username: 'Nita',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Librarian',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-08-25'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'muhammad.farhan@millennia21.id',
        password: 'password123',
        name: 'Muhammad Farhan Sholeh Ramadhika',
        username: 'Farhan',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Design & Social Media',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-08-25'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'fathan.qalbi@millennia21.id',
        password: 'password123',
        name: 'Muhammad Fathan Qorib',
        username: 'Fathan',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Boy',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-02-23'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'awal@millennia21.id',
        password: 'password123',
        name: 'Muhammad Gibran Al Wali',
        username: 'Awal / Gibran',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'PLH',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-18'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'ananta@millennia21.id',
        password: 'password123',
        name: 'Muhammad Rayhan Ananta',
        username: 'Ananta',
        role: 'support_staff',
        department: 'MAD Lab',
        jobLevel: 'Support Staff',
        unit: 'MAD Lab',
        jobPosition: 'IT Support',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-14'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'mukron@millennia21.id',
        password: 'password123',
        name: 'Mukron',
        username: 'Mukron',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'PLH',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-08-28')
    },
    {
        email: 'nadiamws@millennia21.id',
        password: 'password123',
        name: 'Nadia',
        username: 'Nadia',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'English Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-11-18'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'nanda@millennia21.id',
        password: 'password123',
        name: 'Nanda Citra Ryani, S.IP',
        username: 'Nanda',
        role: 'teacher',
        department: 'Kindergarten',
        jobLevel: 'Teacher',
        unit: 'Kindergarten',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2019-04-01')
    },
    {
        email: 'nathasya@millennia21.id',
        password: 'password123',
        name: 'Nathasya Christine Prabowo, S.Si',
        username: 'Thasya',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2023-07-17'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'kusumawantari@millennia21.id',
        password: 'password123',
        name: 'Nazmi Kusumawantari',
        username: 'Mima',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-11-06'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'made@millennia21.id',
        password: 'password123',
        name: 'Ni Made Ayu Juwitasari',
        username: 'Made',
        role: 'staff',
        department: 'Elementary',
        jobLevel: 'Staff',
        unit: 'Elementary',
        jobPosition: 'Secretary',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-07-29'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'nopi@millennia21.id',
        password: 'password123',
        name: 'Nopi Puji Astuti',
        username: 'Nopi',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Girl',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-10-30'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'novan@millennia21.id',
        password: 'password123',
        name: 'Novan Syaiful Rahman',
        username: 'Novan',
        role: 'se_teacher',
        department: 'Junior High',
        jobLevel: 'SE Teacher',
        unit: 'Junior High',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-14'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'novi@millennia21.id',
        password: 'password123',
        name: 'Novia Anggraeni',
        username: 'Novi',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Staff Research & Development',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-08-15'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'novia@millennia21.id',
        password: 'password123',
        name: 'Novia Syifaputri Ramadhan',
        username: 'Novia',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-08-11'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'ismail@millennia21.id',
        password: 'password123',
        name: 'Nur Muhamad Ismail',
        username: 'Ismail',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Staff HCM',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-09-08'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'widya@millennia21.id',
        password: 'password123',
        name: 'Nurul Widyaningtyas Agustin',
        username: 'Widya',
        role: 'teacher',
        department: 'Kindergarten',
        jobLevel: 'Teacher',
        unit: 'Kindergarten',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-09-03'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'pipiet@millennia21.id',
        password: 'password123',
        name: 'Pipiet Anggreiny, S.TP',
        username: 'Pipiet',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-07-17')
    },
    {
        email: 'cecil@millennia21.id',
        password: 'password123',
        name: 'Pricilla Cecil Leander, S.Pd',
        username: 'Cecil',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-08-21')
    },
    {
        email: 'prisy@millennia21.id',
        password: 'password123',
        name: 'Prisy Dewanti',
        username: 'Prisy',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-14'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'putri.fitriyani@millennia21.id',
        password: 'password123',
        name: 'Putri Fitriyani, S.Pd',
        username: 'Putri',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2022-07-18')
    },
    {
        email: 'raisa@millennia21.id',
        password: 'password123',
        name: 'Raisa Ramadhani',
        username: 'Raisa',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-14'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'ratna@millennia21.id',
        password: 'password123',
        name: 'Ratna Merlangen',
        username: 'Ratna',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Director Secretary',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-03-06')
    },
    {
        email: 'restia.widiasari@millennia21.id',
        password: 'password123',
        name: 'Restia Widiasari',
        username: 'Echi',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-09-02'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'rezarizky@millennia21.id',
        password: 'password123',
        name: 'Reza Rizky Prayudha',
        username: 'Reza',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-07-15'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'rifqi.satria@millennia21.id',
        password: 'password123',
        name: 'Rifqi Satria Permana, S.Pd',
        username: 'Rifqi',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'Physical Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-10-07'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'rike@millennia21.id',
        password: 'password123',
        name: 'Rike Rahmawati S.Pd',
        username: 'Rike',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-01-23'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'risma.angelita@millennia21.id',
        password: 'password123',
        name: 'Risma Ayu Angelita',
        username: 'Risma',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-06-24'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'risma.galuh@millennia21.id',
        password: 'password123',
        name: 'Risma Galuh Pitaloka Fahdin',
        username: 'Galuh',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-08-11'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'rizkinurul@millennia21.id',
        password: 'password123',
        name: 'Rizki Nurul Hayati',
        username: 'Kiki',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'Science Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-09-04')
    },
    {
        email: 'robby@millennia21.id',
        password: 'password123',
        name: 'Robby Anggara',
        username: 'Robby',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Boy',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-06-19'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'robby.noer@millennia21.id',
        password: 'password123',
        name: 'Robby Noer Abjuny',
        username: 'Robby',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-09-08'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'robiatul@millennia21.id',
        password: 'password123',
        name: 'Robiatul Adawiah',
        username: 'Lia',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Girl',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-07-10')
    },
    {
        email: 'rohmatulloh@millennia21.id',
        password: 'password123',
        name: 'Rohmatulloh',
        username: 'Roy',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Boy',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-04-03')
    },
    {
        email: 'roma@millennia21.id',
        password: 'password123',
        name: 'Romasta Oryza Sativa Siagian, S.Pd',
        username: 'Tata',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2022-07-18')
    },
    {
        email: 'salsabiladhiyaussyifa@millennia21.id',
        password: 'password123',
        name: 'Salsabila Dhiyaussyifa Laela',
        username: 'Sabil',
        role: 'se_teacher',
        department: 'Elementary',
        jobLevel: 'SE Teacher',
        unit: 'Elementary',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-06-24'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'sarahyuliana@millennia21.id',
        password: 'password123',
        name: 'Sarah Yuliana, SE',
        username: 'Sarah',
        role: 'head_unit',
        department: 'Finance',
        jobLevel: 'Head Unit',
        unit: 'Finance',
        jobPosition: 'Head of Finance',
        employmentStatus: 'Permanent',
        joinDate: new Date('2020-06-24')
    },
    {
        email: 'rain@millennia21.id',
        password: 'password123',
        name: 'Shahrani Fatimah Azzahrah',
        username: 'Rain',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Staff HCM',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-09-02'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'susantika@millennia21.id',
        password: 'password123',
        name: 'Susantika Nilasari',
        username: 'Nila',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Staff CRM',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-11-01'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'tiastiningrum@millennia21.id',
        password: 'password123',
        name: 'Tiastiningrum Nugrahanti, S.Pd',
        username: 'Tyas',
        role: 'se_teacher',
        department: 'Junior High',
        jobLevel: 'SE Teacher',
        unit: 'Junior High',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-08-21')
    },
    {
        email: 'hanny@millennia21.id',
        password: 'password123',
        name: 'Tien Hadiningsih, S.S',
        username: 'Hanny',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Staff CRM',
        employmentStatus: 'Permanent',
        joinDate: new Date('2015-07-27')
    },
    {
        email: 'triayulestari@millennia21.id',
        password: 'password123',
        name: 'Tri Ayu Lestari',
        username: 'Ayu',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-07-15'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'triafadilla@millennia21.id',
        password: 'password123',
        name: 'Tria Fadilla',
        username: 'Tria',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-06-24'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'udom@millennia21.id',
        password: 'password123',
        name: 'Udom Anatapong',
        username: 'Udom',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Driver',
        employmentStatus: 'Permanent',
        joinDate: new Date('2017-09-06')
    },
    {
        email: 'usep@millennia21.id',
        password: 'password123',
        name: 'Usep Saefurohman',
        username: 'Usep',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Driver',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-07-17'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'vickiaprinando@millennia21.id',
        password: 'password123',
        name: 'Vicki Aprinando',
        username: 'Nando',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-08-02'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'vinka@millennia21.id',
        password: 'password123',
        name: 'Vinka Erawati, S.Pd',
        username: 'Vinka',
        role: 'se_teacher',
        department: 'Kindergarten',
        jobLevel: 'SE Teacher',
        unit: 'Kindergarten',
        jobPosition: 'Special Education Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2019-07-09')
    },
    {
        email: 'yohana@millennia21.id',
        password: 'password123',
        name: 'Yohana Setia Risli',
        username: 'Yoh/Yohana',
        role: 'teacher',
        department: 'Kindergarten',
        jobLevel: 'Teacher',
        unit: 'Kindergarten',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2023-02-20'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'yosafat@millennia21.id',
        password: 'password123',
        name: 'Yosafat Imanuel Parlindungan',
        username: 'Yosa',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'Music Teacher',
        employmentStatus: 'Contract',
        joinDate: new Date('2024-01-23'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'oudy@millennia21.id',
        password: 'password123',
        name: 'Zavier Cloudya Mashareen',
        username: 'Oudy',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Homeroom Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2022-10-17')
    },
    {
        email: 'zolla@millennia21.id',
        password: 'password123',
        name: 'Zolla Firmalia Rossa',
        username: 'Zolla',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'Art Teacher',
        employmentStatus: 'Permanent',
        joinDate: new Date('2023-05-02')
    },
    {
        email: 'yeti@millennia21.id',
        password: 'password123',
        name: 'Yeti',
        username: 'Yeti',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Office Girl',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-09-18'),
        endDate: new Date('2025-12-22')
    },
    {
        email: 'danu@millennia21.id',
        password: 'password123',
        name: 'Danu Irwansyah',
        username: 'Danu',
        role: 'support_staff',
        department: 'Operational',
        jobLevel: 'Support Staff',
        unit: 'Operational',
        jobPosition: 'Driver',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-09-22'),
        endDate: new Date('2025-12-22')
    },
    {
        email: 'ari.wibowo@millennia21.id',
        password: 'password123',
        name: 'Ari Wibowo',
        username: 'Ari',
        role: 'staff',
        department: 'MAD Lab',
        jobLevel: 'Staff',
        unit: 'MAD Lab',
        jobPosition: 'Junior Full Stack Web Developer',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-09-25'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'sayed.jilliyan@millennia21.id',
        password: 'password123',
        name: 'Sayed Jilliyan',
        username: 'Jilliyan',
        role: 'staff',
        department: 'MAD Lab',
        jobLevel: 'Staff',
        unit: 'MAD Lab',
        jobPosition: 'Junior Full Stack Web Developer',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-09-25'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'kiki@millennia21.id',
        password: 'password123',
        name: 'Rizki Amalia Fatikhah',
        username: 'Kiki',
        role: 'staff',
        department: 'Directorate',
        jobLevel: 'Staff',
        unit: 'Directorate',
        jobPosition: 'Training Development',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-09-08'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'ian.ahmad@millennia21.id',
        password: 'password123',
        name: 'Ian Ahmad Fauzi',
        username: 'Ian',
        role: 'staff',
        department: 'Finance',
        jobLevel: 'Staff',
        unit: 'Finance',
        jobPosition: 'Staff Finance',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-10-08'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'andre@millennia21.id',
        password: 'password123',
        name: 'Andrean Hadinata',
        username: 'Andre',
        role: 'staff',
        department: 'Junior High',
        jobLevel: 'Staff',
        unit: 'Junior High',
        jobPosition: 'Secretary',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-10-01'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'chaca@millennia21.id',
        password: 'password123',
        name: 'Chantika Nur Febryanti',
        username: 'Chaca',
        role: 'teacher',
        department: 'Elementary',
        jobLevel: 'Teacher',
        unit: 'Elementary',
        jobPosition: 'Integral & Math Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-09-29'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'sisil@millennia21.id',
        password: 'password123',
        name: 'Najmi Silmi Mafaza',
        username: 'Sisil',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'Math Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-10-20'),
        endDate: new Date('2026-06-22')
    },
    {
        email: 'nayandra@millennia21.id',
        password: 'password123',
        name: 'Nayandra Hasan Sudra',
        username: 'Hasan',
        role: 'teacher',
        department: 'Junior High',
        jobLevel: 'Teacher',
        unit: 'Junior High',
        jobPosition: 'Makerspace Teacher',
        employmentStatus: 'Probation',
        joinDate: new Date('2025-10-01'),
        endDate: new Date('2026-06-22')
    }
];

const seedUsersFromData = async () => {
    try {
        // Connect to MongoDB
        await mongoose.connect(process.env.MONGODB_URI);

        console.log('🌱 Seeding users from provided data...');

        // Clear existing users
        await User.deleteMany({});
        console.log('🗑️  Cleared existing users');

        // Process and create users
        for (const userDataItem of userData) {
            // Calculate working period
            if (userDataItem.joinDate) {
                const joinDate = new Date(userDataItem.joinDate);
                const now = new Date();
                const diffTime = Math.abs(now - joinDate);
                const diffDays = Math.ceil(diffTime / (1000 * 60 * 60 * 24));

                userDataItem.workingPeriod = {
                    years: Math.floor(diffDays / 365),
                    months: Math.floor((diffDays % 365) / 30),
                    days: diffDays % 30
                };
            }

            // Ensure all required fields are present
            const userToCreate = {
                name: userDataItem.name,
                email: userDataItem.email,
                password: userDataItem.password,
                username: userDataItem.username,
                role: userDataItem.role,
                department: userDataItem.department,
                jobLevel: userDataItem.jobLevel,
                unit: userDataItem.unit,
                jobPosition: userDataItem.jobPosition,
                employmentStatus: userDataItem.employmentStatus,
                joinDate: userDataItem.joinDate,
                endDate: userDataItem.endDate,
                workingPeriod: userDataItem.workingPeriod,
                isActive: true,
                emailVerified: true
            };

            const user = new User(userToCreate);
            await user.save();
            console.log(`✅ Created user: ${userDataItem.email} (${userDataItem.role})`);
        }

        console.log('🎉 User seeding completed successfully!');
        console.log(`📊 Total users created: ${userData.length}`);

        // Create directorate hierarchy
        const directorateUsers = await User.find({ role: 'directorate' });
        console.log('👥 Directorate members:', directorateUsers.map(u => u.name));

    } catch (error) {
        console.error('❌ Error seeding users:', error);
    } finally {
        await mongoose.connection.close();
        console.log('🔌 Database connection closed');
    }
};

// Run seeder if called directly
if (require.main === module) {
    seedUsersFromData();
}

module.exports = seedUsersFromData;